##### Header #####
# Author: Robert P. McGuinn
# Date started: 20190516
# Purpose: To install key packages

##### Installation/Loading of Packages #####
# install.packages('RCurl')
library(RCurl)
# install.packages('xlsx')
#install.packages('openxlsx')
library(openxlsx)
library(sp)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("rerddap")
library(rerddap)
#install.packages('leaflet')
library(leaflet)
# install.packages('extrafont')
library(extrafont)
# install.packages('RColorBrewer')
library(RColorBrewer)
# install.packages('googlesheets')
library(googlesheets)
# install.packages('googledrive')
library(googledrive)
library(rmarkdown)
library(knitr)
#install.packages("maps")
library(maps)
#install.packages("rgdal")
library(rgdal)
#install('raster')
library(raster)
#install.packages("spocc")
library(spocc)
#install.packages('arcgisbinding')
#install.packages('refinr')
library(refinr)
# install.packages('marmap')
library(marmap)
#install.packages('prettydoc')
library(prettydoc)
#install.packages('robis')
library(robis)
#install.packages('devtools')
library(devtools)
# install.packages("digest")
# install.packages("data.table")
# install.packages("DBI")
# install.packages("assertthat")
# install.packages("Rcpp")
# install.packages("rerddap")
# install.packages("magrittr")
# install.packages("curl")
library(magrittr)
library(Rcpp)
library(assertthat)
library(DBI)
library(devtools)
library(data.table)
library(digest)
library(rerddap)
library(curl)
library(reshape2)
# install.packages("gdoc")
# install.packages("compareDF")
#install.packages("compareDF")
library(compareDF)
#install.packages("flextable")
library(flextable)
#install.packages("officer")
library(officer)
#install.packages("kableExtra")
#library(kableExtra)
#install.packages("worrms")
library(worrms)
# install.packages("taxize")
library(taxize)
# install.packages("devtools")
library(devtools)
#devtools::install_github("iobis/obistools")
library(obistools)
library(jsonlite) #https://cran.r-project.org/web/packages/jsonlite/
library(httr)
# install.packages("rgbif")
library(rgbif)
# install.packages("imager")
library(imager)
library(tools)
library(stringr)

# packages <- c("dplyr", "tidyr", "devtools", "usethis", "roxygen2", "leaflet", "ggplot2", "DT", "scales", "shiny", "sf", "ggmap", "broom", "captioner")
#
#
# for (package in packages) { if (!(package %in% installed.packages())) { install.packages(package) } }
update.packages(ask=FALSE)






