---
title: "plot_db_growth_through_time"
author: "Robert McGuinn"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: html_document
editor_options: 
  chunk_output_type: console
---
# packages

``` {r install_packages, , echo=T, warning=FALSE, message=FALSE}
library(tidyverse)
library(rmarkdown)
library(knitr)
library(flextable)
library(googlesheets)
library(googledrive)
library(openxlsx)
library(scales)
library(extrafont)

```

# load NDB

``` {r data_intake, echo=T, warning=FALSE, message=FALSE, cache=TRUE}
##### input: latest version of NDB #####
setwd("C:/rworking/deepseatools/indata")
indata<-read.csv("DSCRTP_NatDB_20191217-0.csv", header = T)
filt <- indata %>%
  filter(Flag == "0")

##### remove files #####
rm(indata)

```

# clean NDB

```{r clean, echo=T, warning=FALSE, message=FALSE}
##### data improvements (from version DSCRTP_NatDB_20191217-0)#####

filt <- filt %>% mutate(DataProvider =
                          ifelse(DataProvider == "California Academy of Sciences (CAS)",
                                              'California Academy of Sciences',
                                              as.character(DataProvider)))

filt <- filt %>% mutate(DataProvider =
                          ifelse(DataProvider == "NOAA, Office of Exploration and Research | Hawai’i Undersea Research Laboratory, University of Hawai’i", "NOAA, Office of Exploration and Research | Hawai'i Undersea Research Laboratory, University of Hawai'i", 
                                 as.character(DataProvider)))

```

# load NDB_trajectory

```{r}

# read the file into R as a data frame from xl
traj <- read.xlsx('../indata/NDB_trajectory.xlsx')

## checking
# names(traj)
# View(traj)
# plot(traj$totrecords)
# plot(traj$corrected)
# plot(traj$quarter)
# plot(traj %>% filter(is.na(totrecords) == F) %>% pull(totrecords))
# plot(traj$totrecord)
# plot(traj$totrecords,as.Date(traj$text_date_posted))
# plot(as.Date(traj$text_date_posted), traj$totrecords)

```

# load DatasetID Key

``` {r merge_key, eval=T}

x <- drive_find(q = "name contains '20191217-0_DatasetID_Key_DSCRTP'")

# # browse to it
# x %>% drive_browse()
# getting the id as a character string
y <- x$id

# this downloads the file to the specified path
dl <- drive_download(as_id(y), path = "C:/rworking/deepseatools/indata/20191217-0_DatasetID_Key_DSCRTP.xlsx", overwrite = TRUE)

# read the file into R as a data frame
key <- read.xlsx(dl$local_path)
d <- merge(filt, key, all.x = TRUE)

##### remove data ##### 
rm(filt)

```

# set up knitr options

``` {r setup_opts, echo=T, warning=FALSE, message=FALSE}

##### knitr options #####
knitr::opts_chunk$set(
  fig.width = 8.0, 
  fig.asp = .5, 
  warning = FALSE,
  message=FALSE,
  cache = TRUE,
  dpi = 300, 
  dev = c('png'), cache.lazy = FALSE, 
  fig.path="C:/rworking/deepseatools/reports/figures/") 

##### setting scientific notation and digits options
options(scipen=10000)
options(digits = 3)

```

# prep the data 

```{r new_and_corrected, echo=F, eval=T, warning=F, message=F}

d <- traj %>%
 pivot_longer(cols = c(totrecords, newrecords, corrected), names_to = "type", values_to = "count")

d2 <- d %>% group_by(fy,type) %>% 
  summarize(sum = sum(count, na.rm = T), max = max(count, na.rm = T)) %>% 
  mutate(merge = ifelse(type == "totrecords", max, sum))

d3 <- d2 %>% filter(type != "totrecords") %>% 
  group_by(fy) %>% 
  summarize(sum2 = sum(sum, na.rm = T))

d4 <- merge(d2,d3, all.x = T)

d5 <- d4 %>%  mutate(sum3 = ifelse(type == "totrecords", 
                                   merge - sum2, 
                                   merge))%>% 
  filter(fy != 2015) %>% 
  filter(fy != 2020)

d5$type <- factor(d5$type)
levels(d5$type)
levels(d5$type) <- c("Improved", "New", "Un-touched")

```

# stacked bar chart

```{r}

cl <- colors(distinct = TRUE)
set.seed(13) # to set random generator seed
mycols <- sample(cl, 3)

ggplot(d5, aes(fill=type, y=sum3, x=fy)) + 
    geom_bar(position="stack", stat="identity") +
scale_colour_manual(values = mycols, 
                    aesthetics = c("colour", "fill"),
                    drop = FALSE, 
                    guide=guide_legend(reverse=F)) + 
  scale_y_continuous(labels = comma) +
  theme_bw() +
  theme(text=element_text(size=14,  family="Cambria")) +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.title = element_blank()) +
  theme(axis.title.x = element_text(vjust=-2.5)) +
  theme(plot.margin = unit(c(1,1,1,1), "cm"))+
  ggtitle("Proportion of new and improved records") + 
  theme(plot.title = element_text(size=15)) +
  theme(axis.title.y = element_text(vjust=5)) +
  xlab('Fiscal Year') +
  ylab('Number of Records')


```

# save the figure

```{r}

ggsave(paste("c:/rworking/deepseatools/images/", "20200306-0_new_improved_RPMcGuinn", ".png", sep = ''), 
         width = 6.5, 
         height = 5.57, 
         units = "in")

```

# make some calculations 

```{r}

```





