---
title: "Quarterly Checker"
author: "Robert McGuinn"
date: "2021-06-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages

```{r}
library(googledrive)
library(openxlsx)
library(usethis)
library(tidyverse)
library(sf)
library(leaflet)
```

# get XLS file from Google Drive

```{r}
# set name of the file
filename <- '20200731_Shuler_NF1901'
# find the file in google drive by name
x <- drive_find(q = paste("name contains ", "'", filename, "'", sep = ''))
# getting the id as a character string
y <- x$id
# this downloads the file to the specified path
dl <- drive_download(as_id(y), path = "C:/rworking/deepseatools/indata/sheet.xlsx", overwrite = TRUE)
# read the file into R as a data frame
sheet <- read.xlsx(dl$local_path, sheet = 4, startRow = 13)
head(sheet)
```

# get zip file from Google Drive and pull out specific CSV, load to R

```{r}
# set the file name (user supplied th file name root, without extension)
filename <- '20211008-0_NOAA_NEFSC_Connecticut_Kraken_2_ROV_Dives_2_to_15_Packer_2014_2014'
# find the file in google drive by name
x <- drive_find(q = paste("name contains ", "'", filename,".zip", "'", sep = ''))
# getting the id as a character string
y <- x$id
# download the zip file
dl <- drive_download(as_id(y), path = "C:/rworking/deepseatools/indata/file.zip", overwrite = TRUE)
# extract just the file of interest from the zip file
sub <- read.csv(unz(dl$local_path, paste(filename, ".csv", sep = '')))

```

# gis inspection and export

```{r}o

##### create x from sub #####
x <- sub

##### filter data #####

# get rid of any missing Latitudes or Longitudes
x <- x %>% filter(Latitude != -999 | 
                    Longitude != -999, 
                   # FlagReason== "Horizontal position or depth is questionable", 
                   # EventID == 'H1568'
                    )

## checking 

yo <- x %>% 
  group_by(CatalogNumber, Latitude, Longitude, Flag, FlagReason) %>% 
  summarize(n=n()) %>% View()


# make copy to turn into spatial points data frame.
x_geo <- x

##### create simple features object data frame #####
projcrs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
x_geo_sf <- st_as_sf(x = x_geo,                         
           coords = c("Longitude", "Latitude"),
           crs = projcrs)

##### thin down the variables #####
x_geo_export <- x_geo_sf %>% dplyr::select(CatalogNumber, Phylum, ScientificName, SampleID, DepthInMeters, SurveyID, EventID, Flag, ImageURL)

##### make a leaflet map #####
library(leaflet)
m <- leaflet() %>% setView(lng = 5,lat = 38, zoom = 1)
m <- addProviderTiles(m, "Esri.OceanBasemap",  options = providerTileOptions(noWrap = TRUE))
m <- addCircleMarkers(m, data=x_geo_export, 
                        radius=5, 
                        weight=0, 
                        fillColor= "blue", 
                        fillOpacity=1,
                        popup = paste(
                          "<b><em>","Catalog Number:","</b></em>", x_geo_export$CatalogNumber, "<br>",
                          "<b><em>","Sample ID:","</b></em>", x_geo_export$SampleID, "<br>",
                          "<b><em>","Scientific Name:","</b></em>", x_geo_export$ScientificName, "<br>",
                          "<b><em>","Depth (meters):","</b></em>", x_geo_export$DepthInMeters, "<br>",
                          "<b><em>","Survey ID:","</b></em>", x_geo_export$SurveyID, "<br>",
                          "<b><em>","Event ID:","</b></em>", x_geo_export$EventID, "<br>",
                          "<b><em>","Flag:","</b></em>", x_geo_export$Flag, "<br>",
                          "<b><em>","Image:","</b></em>", x_geo_export$ImageURL)
                                  
  )
m

##### Optional: export data it will guess the driver automatically based on the .shp extension #####
# st_write(x_geo_export, "C:/Users/Robert.Mcguinn/Documents/ArcGIS/Projects/fromr/shapefiles/x_geo_export.shp", delete_dsn = T)

## checking 



```

