---
title: "taxonomy_checker"
author: "Robert McGuinn"
date: "3/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
# opts

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# packages

```{r}
library(tidyverse)
library(googledrive)
library(googlesheets)
library(worrms)
library(rmarkdown)
library(knitr)
```

# load taxonomy tables

```{r}
##### load the most current taxonomy from Google Sheets #####
# https://drive.google.com/open?id=0B9c2c_XdhpFBT29NQmxIeUQ4Tlk

n <- '20200313-0'

taxfl <- gs_title(paste(n, '_taxonomy_to_flag',sep = ''))
#gs_browse(taxfl)
taxfl <- gs_read(taxfl)

taxch <- gs_title(paste(n, '_taxonomy_to_change', sep = ''))
#gs_browse(taxch)
taxch <- gs_read(taxch)

tax <- gs_title(paste(n, '_taxonomy', sep = ''))
#gs_browse(tax)
tax <- gs_read(tax)
```

# load dataset of interest 

```{r}
x <- '20200324-1_NOAA_AFSC_Oscar_Dyson_OD2017-06_Jones_Wilborn_Goddard_2017_2017'
setwd("C:/rworking/deepseatools/indata")
sub <- read.csv(paste(x,'.csv', sep = ''), header = T) 

##### --OR-- get dataset via Excel #####
setwd("C:/rworking/deepseatools/indata")
sub <- read.xlsx('20200313-0_NMNH-NewRecords_11-2019a_THourigan.xlsx', sheet = 1)
```

# create taxa list 4 possible ways

```{r}
##### create a character vector of non-matching taxa #####
taxa <- as.character(
  setdiff(unique(sub$ScientificName),
          tax$ScientificName)
  )

## checking
# taxa
# length(taxa)

##### -OR- just bring in a list of mismatches from csv #####

# setwd("C:/rworking/deepseatools/indata")
# taxa <- read.csv('taxa.csv', header = F)
# taxa$V1 <- gsub("'", '', taxa$V1)

##### -OR- bring in a single taxa

#taxa <- as.character("Chrysogorgia binata")

##### -OR- just bring in all of the taxa from the sub
# taxa <- unique(sub$ScientificName)
```

# clean taxa list 

```{r}

taxa <- taxa %>% str_replace(' sp.', '')
taxa <- taxa %>% str_replace('cf. ', '')
taxa <- setdiff(taxa, tax$ScientificName)
taxa <- trimws(taxa)
taxa <- str_sort(taxa)

```

# check taxa list 

```{r}

length(taxa)
length(setdiff(sub$AphiaID, tax$AphiaID))

```

# match taxa (nonmatching taxa will not show)

```{r}

for (val in taxa)
{
  tryCatch({
  x <- wm_records_taxamatch(name = val,
                            ids = TRUE,
                            verbose = TRUE,
                            marine_only = TRUE,
                            sleep_btw_chunks_in_sec = 0.2
  )

  x <- x[[1]]
  x$VerbatimScientificName <- val
  assign(paste('spec', str_replace(val, ' ', '_'), sep='_'), x)
  }, error=function(e){})
}

z <- mget(ls(pattern='spec')) %>%
              bind_rows()

## checking
# z %>% select(VerbatimScientificName,
#              scientificname,
#              valid_name) %>% View()
# 
# x <- tax %>%  filter(tax$ScientificName %in% z$scientificname) %>% 
#   select(ScientificName, AphiaID)
# View(x)
# 
# setdiff(x$AphiaID, z$AphiaID)
# setdiff(z$AphiaID, x$AphiaID)

## cleanup
# rm(list = ls(pattern = 'spec'))
# rm(z)


```

# creating a new taxonomy table

```{r}

##### creating an empty taxonomy table (using information from accepted names) to populate (output: newtax_un) #####
newtax <- tax[0,]

#adding enough empty rows
newtax[1:length(z$scientificname),] <- NA

```

# bringing info from taxonomic match table (z)

```{r}

##### adding information from (match from Worms) to taxonomy table #####
newtax$ScientificName <- z$valid_name
newtax$AphiaID <- z$valid_AphiaID
newtax$ScientificNameAuthorship <- z$valid_authority
newtax$Phylum <- z$phylum
newtax$Class <- z$class
newtax$Order <- z$order
newtax$Family <- z$family
newtax$Genus <- z$genus
newtax$TaxonRank <- tolower(z$rank)
newtax$SynonymAphiaID <- "-999"
newtax$HigherTaxonNameAuthorship <- NA

```

# joining new records with taxonomy table 

```{r}

##### binding new taxonomy table with existing #####
newtax <- rbind(tax, newtax)

## checking
# length(tax$VernacularNameCategory)
# length(newtax$VernacularNameCategory)

```

# write updated taxonomy table to file

```{r}

##### write out new file #####
setwd("C:/rworking/deepseatools/indata")
newtax %>%
  write.csv('newtax.csv', row.names = FALSE)

```






