---
title: "Transform EX1907 data from wide to long"
author: "Robert McGuinn"
date: "2020-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages

```{r}
library(googledrive)
library(openxlsx)
library(tidyverse)
```

# get XLS file from Google Drive

```{r}
##  set google ID of file
# id <- "1qf76RNErEJXfr_48rRCY4mBi7-OgG6t1"
id <- "1aPJHwJW3tI-C-LdemTj97zlfEPTyJjuN"

# this downloads the file to the specified path
dl <- drive_download(as_id(id), path = "C:/rworking/deepseatools/indata/sheet.xlsx", overwrite = TRUE)

# read the file into R as a data frame
sheet <- read.xlsx(dl$local_path, sheet = 1, startRow = 1)

## check 
# View(sheet)
# names(sheet)

## cleanup

```

# transform from wide to long

```{r}
##### extract each layer  #####
positions <- c(1:25)
x1 <- sheet %>% dplyr::select(all_of(positions))

positions2 <- c(6:12, 19:24, 26:37)
x2 <- sheet %>% dplyr::select(all_of(positions2))

positions3 <- c(6:12, 19:24, 38:49)
x3 <- sheet %>% dplyr::select(all_of(positions3))

positions4 <- c(6:12, 19:24, 50:61)
x4 <- sheet %>% dplyr::select(all_of(positions4))

positions5 <- c(6:12, 19:24, 62:73)
x5 <- sheet %>% dplyr::select(all_of(positions5))

##### make the names the same ##### 
names(x2) <- gsub(x = names(x2), pattern = "2", replacement = "") 
names(x3) <- gsub(x = names(x3), pattern = "3", replacement = "")
names(x4) <- gsub(x = names(x4), pattern = "4", replacement = "")
names(x5) <- gsub(x = names(x5), pattern = "5", replacement = "")

##### rbind all of them together ##### 
longdf <- do.call("rbind", list(x1,x2,x3,x4,x5))

## checking 
# x <- longdf %>% filter(is.na(SampleID) == T)
# x

##### fixing SampleID across all records ##### 
longdf$SampleID <- sheet$SampleID

## checking
# longdf %>% filter(ScientificName == '') %>% pull(ScientificName) %>% length()
# longdf %>% filter(is.na(ScientificName) == T) %>% pull(ScientificName) %>% length()

##### remove NA #####
longdf <- longdf %>% filter(is.na(ScientificName) == F)
longdf <- longdf %>% filter(ScientificName != '')

# check 
# x <- longdf %>% filter(is.na(SampleID) == T)

##### fix TransectID/SampleID #####
## first get all blanks in Tracking ID to be NA
longdf <- longdf %>% mutate(TrackingID = ifelse(TrackingID == '', NA, TrackingID))

## check
# longdf %>% filter(is.na(SampleID) == T) %>% pull(SampleID) %>% length()
# longdf %>% filter(is.na(TrackingID) == F) %>% pull(TrackingID) %>% View()
# longdf %>% filter(is.na(TrackingID) == F) %>% group_by(SampleID, TrackingID) %>% summarize(n=n()) %>% View()
# longdf %>% filter(is.na(TrackingID) == F) %>% pull(TrackingID) %>% View()
# longdf %>% pull(TrackingID) %>% table(useNA = 'always') %>% View()
# longdf %>% filter(grepl('.jpg', SampleID)) %>% pull(SampleID) %>% length()

##### isolate those SampleIDs where there is a TrackingID #####
# EX1907_D01_04B EX1907_IMG_20191101T194639Z_ROVHD.jpg
# EX1907_D03_01B EX1907_IMG_20191103T183400Z_ROVHD.jpg

longdf <- longdf %>% mutate(SampleID = ifelse(is.na(TrackingID) == T &
                           SampleID == "EX1907_D01_04B" , 
                         "EX1907_IMG_20191101T194639Z_ROVHD.jpg", 
                         SampleID))

longdf <- longdf %>% mutate(SampleID = ifelse(is.na(TrackingID) == T &
                           SampleID == "EX1907_D03_01B" , 
                         "EX1907_IMG_20191103T183400Z_ROVHD.jpg", 
                         SampleID))

##### checking #####
# longdf %>% 
#   filter(SampleID == "EX1907_IMG_20191101T194639Z_ROVHD.jpg") %>% 
#            group_by(SampleID, TrackingID) %>% summarize(n=n()) %>% 
#            View()
# 
# longdf %>% 
#   filter(SampleID == "EX1907_IMG_20191103T183400Z_ROVHD.jpg") %>% 
#            group_by(SampleID, TrackingID) %>% summarize(n=n()) %>% 
#            View()
# 
# View(longdf$SampleID)

```

# write to CSV

```{r}
# write.csv(longdf, "c:/rworking/deepseatools/indata/20210107_test_file_RPMcGuinn.csv", row.names = F)

write.xlsx(longdf, "c:/rworking/deepseatools/indata/20210107-1_test_file_RPMcGuinn.xlsx", row.names = F)

```






