---
title: 'DataProvider Table (NDB 20191217-0)'
output: 
    word_document:
      reference_docx: c:\rworking\deepseatools\wordtemplates\mytemplate.docx
      
---

``` {r setup_opts, , echo=FALSE, warning=FALSE, message=FALSE}

##### knitr options #####
knitr::opts_chunk$set(
  fig.width = 8, 
  fig.asp = .4, 
  warning = FALSE,
  message=FALSE,
  cache = TRUE,
  dpi = 300, 
  dev = c('png'), cache.lazy = FALSE, 
  fig.path="C:/rworking/deepseatools/reports/2019_status_update_report/figures/") 

options(scipen=10000)

##### setting digit options #####
options(digits = 0)
```

``` {r data_intake, echo=FALSE, warning=FALSE, message=FALSE, eval = T}

##### input: latest version of NDB #####
setwd("C:/rworking/deepseatools/indata")
indata<-read.csv("DSCRTP_NatDB_20191217-0.csv", header = T)
filt <- indata %>%
  filter(Flag == "0")

```

``` {r merge_key, echo=F, eval=T,}
x <- drive_find(q = "name contains '20191217-0_DatasetID_Key_DSCRTP'")

# # browse to it
# x %>% drive_browse()

# getting the id as a character string
y <- x$id

# this downloads the file to the specified path
dl <- drive_download(as_id(y), path = "C:/rworking/deepseatools/indata/20191217-0_DatasetID_Key_DSCRTP.xlsx", overwrite = TRUE)

# read the file into R as a data frame
key <- read.xlsx(dl$local_path)
d <- merge(filt, key, all.x = TRUE)
```

``` {r data_prep, echo=FALSE, warning=FALSE, message=FALSE}

##### data improvements (from version DSCRTP_NatDB_20191217-0)#####

filt <- filt %>% mutate(DataProvider =
                          ifelse(DataProvider == "California Academy of Sciences (CAS)",
                                              'California Academy of Sciences',
                                              as.character(DataProvider)))

filt <- filt %>% mutate(DataProvider =
                          ifelse(DataProvider == "NOAA, Office of Exploration and Research | Hawai’i Undersea Research Laboratory, University of Hawai’i", "NOAA, Office of Exploration and Research | Hawai'i Undersea Research Laboratory, University of Hawai'i", 
                                 as.character(DataProvider)))

                       
##### checker #####

# length(filt1$CatalogNumber)

# sum_tbl <- filt %>%
#    # filter(as.numeric(IndividualCount) > 100,
#    #        grepl('Etnoyer', PI),
#    #        DatasetID == 'NOAA_SJ-10-08'
#    #       ) %>%
#   group_by(AccessionID) %>% 
#   summarize(DataProvider = toString(unique(DataProvider)),
#             Repository = toString(unique(Repository)),
#             Vessel = toString(unique(Vessel)),
#             PI = toString(unique(PI)),
#             SampleID = toString(unique(SampleID)),
#             ScientificName = toString(unique(ScientificName)),
#             ImageFilePath = toString(unique(ImageFilePath)),
#             Records = n()
#   ) %>% 
#   arrange(desc(Records))
# View(sum_tbl)

```

``` {r schema, echo=FALSE, cache = FALSE, warning=FALSE, message=FALSE, eval=F}
##### download Google Sheet version of schema for use in R  documents ##### 
# Register and download Google Sheet
s <- gs_title('2019_DSCRTP_National_Database_Schema')
#s <- gs_key('1YDskzxY8OF-34Q8aI04tZvlRbhGZqBSysuie39kYHoI')
s <- gs_read(s)
# s<- s[,-(33:35)]
#names(s)

```

``` {r dataprovider_table, echo=FALSE}

x <-
  d %>%
  group_by(DataProvider, class) %>% 
  summarize(#class = paste(unique(class), collapse= " | "),
            #Number_Datasets = length(unique(DatasetID)),
            DatasetIDs = paste(unique(DatasetID), collapse= " | "),
    Records = n()
            )

x <- x[,c("DataProvider","DatasetIDs","class","Records")]

colkeys <- col_keys <- c("Records")

ft <- flextable(x) %>% 
  theme_box() %>% #booktabs, vanilla, box, tron, tron_legacy
  colformat_num(col_keys = colkeys, digits = 0, big.mark = ",", na_str = "NA") %>% 
  font(fontname = "Cambria", part = "all") %>% #header, body, all
  fontsize(size = 10) %>% 
  flextable::width(j = ~ DatasetIDs + DataProvider, width = 2.5) %>%
  flextable::width(j = ~ class, width = .9) %>%
  merge_v(j = c('DataProvider')) %>% 
  set_header_labels(class = "Type of Data",
                    Records = "# of Records")
ft

```


