---
title: 'NOAA National Database for Deep-Sea Corals and Sponges'
output: 
    word_document:
      reference_docx: c:\rworking\deepseatools\wordtemplates\mytemplate1.docx
      
---

``` {r setup_opts, , echo=FALSE, warning=FALSE, message=FALSE}

##### knitr options #####
knitr::opts_chunk$set(
  fig.width = 8, 
  fig.asp = .4, 
  warning = FALSE,
  message=FALSE,
  cache = TRUE,
  dpi = 300, 
  dev = c('png'), cache.lazy = FALSE, 
  fig.path="C:/rworking/deepseatools/reports/2019_status_update_report/figures/") 

options(scipen=10000)

##### setting digit options #####
options(digits = 0)
```

``` {r data_intake, echo=FALSE, warning=FALSE, message=FALSE, eval = F}

##### input: latest version of NDB #####
setwd("C:/rworking/deepseatools/indata")
indata<-read.csv("DSCRTP_NatDB_20191217-0.csv", header = T)
filt <- indata %>%
  filter(Flag == "0")

```

``` {r schema, echo=FALSE, cache = FALSE, warning=FALSE, message=FALSE, eval=F}
##### download Google Sheet version of schema for use in R  documents ##### 
# Register and download Google Sheet
s <- gs_title('2019_DSCRTP_National_Database_Schema')
#s <- gs_key('1YDskzxY8OF-34Q8aI04tZvlRbhGZqBSysuie39kYHoI')
s <- gs_read(s)
# s<- s[,-(33:35)]
#names(s)

```

``` {r dataprovider_table, echo=FALSE}
# options(scipen=999)
# create a list of files (or single file) that meets title query
# x <- drive_find(q = "name contains '20191217-0_DatasetID_Key_DSCRTP'")
# 
# # # browse to it
# # x %>% drive_browse()
# 
# # getting the id as a character string
# y <- x$id
# 
# # this downloads the file to the specified path
# dl <- drive_download(as_id(y), path = "C:/rworking/deepseatools/indata/20191217-0_DatasetID_Key_DSCRTP.xlsx", overwrite = TRUE)
# 
# # read the file into R as a data frame
# key <- read.xlsx(dl$local_path)
# d <- merge(filt, key, all.x = TRUE)

# checking merge step
# View(d %>% filter(DataProvider == 'Ross (2012)') %>% 
#   group_by(DatasetID, DataProvider, class) %>% 
#   summarize(n=n()))

x <-
  d %>%
  group_by(DataProvider) %>% 
  summarize(class = paste(unique(class), collapse= " | "),
            #Number_Datasets = length(unique(DatasetID)),
            DatasetIDs = paste(unique(DatasetID), collapse= " | "),
    Records = n()
            )

colkeys <- col_keys <- c("Records")

ft <- flextable(x) %>% 
  theme_box() %>% #booktabs, vanilla, box, tron, tron_legacy
  colformat_num(col_keys = colkeys, digits = 0, big.mark = ",", na_str = "NA") %>% 
  font(fontname = "Cambria", part = "all") %>% #header, body, all
  fontsize(size = 10) %>% 
  width(j = ~ DatasetIDs + DataProvider, width = 2.5) %>%
  width(j = ~ class, width = .9) %>%
  #merge_v(j = c('class')) %>% 
  set_header_labels(class = "Type of Data",
                    Records = "# of Records")
ft

```
